# Keep project-specific support rules here.
# You can use `-keep class` or `-dontwarn` to suppress warnings.
# Do not edit this file unless you know the consequences.

# Prevent library warnings from being treated as errors in release.
-dontwarn com.github.barteksc.pdfviewer.**
-dontwarn com.tom_roush.pdfbox.**
